"""Initial schema migration

Revision ID: 205c4bfab43b
Revises: 
Create Date: 2026-08-13 01:28:00.815254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205c4bfab43b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_domain_id', backend.app.models.GUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_domain_id'], ['domains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('career_goal', sa.Text(), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('github_access_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_username')
    )
    op.create_table('career_snapshots',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=True),
    sa.Column('dominant_domains', sa.JSON(), nullable=True),
    sa.Column('emerging_domains', sa.JSON(), nullable=True),
    sa.Column('strongest_skills', sa.JSON(), nullable=True),
    sa.Column('active_projects', sa.JSON(), nullable=True),
    sa.Column('career_direction', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain_progress',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('domain_id', backend.app.models.GUID(), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('depth_score', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('trajectory', sa.String(length=50), nullable=True),
    sa.Column('first_detected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_identifier', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('individual_or_team', sa.String(length=50), nullable=True),
    sa.Column('sync_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_requirements',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('role_id', backend.app.models.GUID(), nullable=False),
    sa.Column('skill_id', backend.app.models.GUID(), nullable=True),
    sa.Column('domain_id', backend.app.models.GUID(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_progress',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('skill_id', backend.app.models.GUID(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('usage_frequency', sa.Float(), nullable=True),
    sa.Column('depth_score', sa.Float(), nullable=True),
    sa.Column('recency_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('trajectory', sa.String(length=50), nullable=True),
    sa.Column('current_level', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('project_id', backend.app.models.GUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_inferences',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('project_id', backend.app.models.GUID(), nullable=True),
    sa.Column('prompt_type', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=True),
    sa.Column('input_payload', sa.Text(), nullable=False),
    sa.Column('response_payload', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_inferences_content_hash'), 'ai_inferences', ['content_hash'], unique=False)
    op.create_table('claims',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('project_id', backend.app.models.GUID(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ideas',
    sa.Column('id', backend.app.models.GUID(), nullable=False),
    sa.Column('user_id', backend.app.models.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('maturity', sa.String(length=50), nullable=True),
    sa.Column('parent_project_id', backend.app.models.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_domains',
    sa.Column('project_id', backend.app.models.GUID(), nullable=False),
    sa.Column('domain_id', backend.app.models.GUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'domain_id')
    )
    op.create_table('project_skills',
    sa.Column('project_id', backend.app.models.GUID(), nullable=False),
    sa.Column('skill_id', backend.app.models.GUID(), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_strength', sa.Float(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id')
    )
    op.create_table('claim_evidence',
    sa.Column('claim_id', backend.app.models.GUID(), nullable=False),
    sa.Column('evidence_id', backend.app.models.GUID(), nullable=False),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_evidence')
    op.drop_table('project_skills')
    op.drop_table('project_domains')
    op.drop_table('ideas')
    op.drop_table('claims')
    op.drop_index(op.f('ix_ai_inferences_content_hash'), table_name='ai_inferences')
    op.drop_table('ai_inferences')
    op.drop_table('activities')
    op.drop_table('skill_progress')
    op.drop_table('role_requirements')
    op.drop_table('projects')
    op.drop_table('evidence')
    op.drop_table('domain_progress')
    op.drop_table('career_snapshots')
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_table('domains')
    # ### end Alembic commands ###
